import type { Product, Service } from "@/types";

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Robe Tempête",
    slug: "robe-tempete",
    description:
      "Robe longue fluide créée par notre styliste, inspirée des mouvements de la mer. Tissu léger et aérien, coupe asymétrique unique. Pièce originale fabriquée à la main dans notre atelier.",
    price: 189.0,
    image: "/images/products/robe-tempete.jpg",
    images: ["/images/products/robe-tempete.jpg", "/images/products/robe-tempete-2.jpg"],
    category: "robes",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Noir Abyssal", "Bleu Océan", "Blanc Écume"],
    inStock: true,
    featured: true,
  },
  {
    id: "prod-2",
    name: "Veste Cyclone",
    slug: "veste-cyclone",
    description:
      "Veste structurée aux lignes dynamiques et au col sculptural. Mélange de coton bio et lin, doublure soyeuse. Design exclusif signé Maelstrom.",
    price: 245.0,
    image: "/images/products/veste-cyclone.jpg",
    images: ["/images/products/veste-cyclone.jpg"],
    category: "vestes",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gris Orage", "Noir Profond", "Bordeaux"],
    inStock: true,
    featured: true,
  },
  {
    id: "prod-3",
    name: "Pantalon Courant",
    slug: "pantalon-courant",
    description:
      "Pantalon ample taille haute avec des plis origami uniques. Tissu drapé fluide qui suit chacun de vos mouvements. Élégance et confort au quotidien.",
    price: 145.0,
    image: "/images/products/pantalon-courant.jpg",
    images: ["/images/products/pantalon-courant.jpg"],
    category: "pantalons",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Noir", "Camel", "Vert Forêt"],
    inStock: true,
    featured: true,
  },
  {
    id: "prod-4",
    name: "Top Brise",
    slug: "top-brise",
    description:
      "Top asymétrique avec drapé artistique. Coton biologique teinté à la main avec des nuances subtiles. Chaque pièce est légèrement unique.",
    price: 89.0,
    image: "/images/products/top-brise.jpg",
    images: ["/images/products/top-brise.jpg"],
    category: "tops",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Indigo", "Terre Cuite", "Blanc Cassé"],
    inStock: true,
    featured: false,
  },
  {
    id: "prod-5",
    name: "Jupe Tourbillon",
    slug: "jupe-tourbillon",
    description:
      "Jupe midi avec mouvement rotatif dramatique. Double épaisseur de mousseline sur base satin. Fermeture invisible sur le côté.",
    price: 135.0,
    image: "/images/products/jupe-tourbillon.jpg",
    images: ["/images/products/jupe-tourbillon.jpg"],
    category: "jupes",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Noir", "Prune", "Bleu Nuit"],
    inStock: true,
    featured: true,
  },
  {
    id: "prod-6",
    name: "Chemise Zéphyr",
    slug: "chemise-zephyr",
    description:
      "Chemise oversize en lin lavé avec détails de couture apparente. Boutons en nacre naturelle. Confort et élégance pour toutes les saisons.",
    price: 115.0,
    image: "/images/products/chemise-zephyr.jpg",
    images: ["/images/products/chemise-zephyr.jpg"],
    category: "chemises",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blanc", "Sable", "Bleu Ciel"],
    inStock: true,
    featured: false,
  },
  {
    id: "prod-7",
    name: "Manteau Ouragan",
    slug: "manteau-ouragan",
    description:
      "Manteau long en laine mérinos avec cape intégrée amovible. Silhouette dramatique, doublure en soie. Pièce maîtresse de la collection.",
    price: 395.0,
    image: "/images/products/manteau-ouragan.jpg",
    images: ["/images/products/manteau-ouragan.jpg"],
    category: "manteaux",
    sizes: ["S", "M", "L"],
    colors: ["Noir", "Anthracite"],
    inStock: true,
    featured: true,
  },
  {
    id: "prod-8",
    name: "Combinaison Flux",
    slug: "combinaison-flux",
    description:
      "Combinaison pantalon ajustée avec ceinture obi. Crêpe de viscose fluide et confortable. Fermeture éclair dos invisible.",
    price: 210.0,
    image: "/images/products/combinaison-flux.jpg",
    images: ["/images/products/combinaison-flux.jpg"],
    category: "combinaisons",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Noir", "Vert Émeraude", "Rouille"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-01",
    name: "Cravatte Numéro 01",
    slug: "cravatte-01",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-01.jpeg",
    images: ["/images/products/cravattes/cravatte-01.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-02",
    name: "Cravatte Numéro 02",
    slug: "cravatte-02",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-02.jpeg",
    images: ["/images/products/cravattes/cravatte-02.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-03",
    name: "Cravatte Numéro 03",
    slug: "cravatte-03",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-03.jpeg",
    images: ["/images/products/cravattes/cravatte-03.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-04",
    name: "Cravatte Numéro 04",
    slug: "cravatte-04",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-04.jpeg",
    images: ["/images/products/cravattes/cravatte-04.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-05",
    name: "Cravatte Numéro 05",
    slug: "cravatte-05",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-05.jpeg",
    images: ["/images/products/cravattes/cravatte-05.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-06",
    name: "Cravatte Numéro 06",
    slug: "cravatte-06",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-06.jpeg",
    images: ["/images/products/cravattes/cravatte-06.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-07",
    name: "Cravatte Numéro 07",
    slug: "cravatte-07",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-07.jpeg",
    images: ["/images/products/cravattes/cravatte-07.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-08",
    name: "Cravatte Numéro 08",
    slug: "cravatte-08",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-08.jpeg",
    images: ["/images/products/cravattes/cravatte-08.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-09",
    name: "Cravatte Numéro 09",
    slug: "cravatte-09",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-09.jpeg",
    images: ["/images/products/cravattes/cravatte-09.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-10",
    name: "Cravatte Numéro 10",
    slug: "cravatte-10",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-10.jpeg",
    images: ["/images/products/cravattes/cravatte-10.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-11",
    name: "Cravatte Numéro 11",
    slug: "cravatte-11",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-11.jpeg",
    images: ["/images/products/cravattes/cravatte-11.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-12",
    name: "Cravatte Numéro 12",
    slug: "cravatte-12",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-12.jpeg",
    images: ["/images/products/cravattes/cravatte-12.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-13",
    name: "Cravatte Numéro 13",
    slug: "cravatte-13",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-13.jpeg",
    images: ["/images/products/cravattes/cravatte-13.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-14",
    name: "Cravatte Numéro 14",
    slug: "cravatte-14",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-14.jpeg",
    images: ["/images/products/cravattes/cravatte-14.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-15",
    name: "Cravatte Numéro 15",
    slug: "cravatte-15",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-15.jpeg",
    images: ["/images/products/cravattes/cravatte-15.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-16",
    name: "Cravatte Numéro 16",
    slug: "cravatte-16",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-16.jpeg",
    images: ["/images/products/cravattes/cravatte-16.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-17",
    name: "Cravatte Numéro 17",
    slug: "cravatte-17",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-17.jpeg",
    images: ["/images/products/cravattes/cravatte-17.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-18",
    name: "Cravatte Numéro 18",
    slug: "cravatte-18",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-18.jpeg",
    images: ["/images/products/cravattes/cravatte-18.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "cravatte-19",
    name: "Cravatte Numéro 19",
    slug: "cravatte-19",
    description: "Cravatte élégante pour sublimer votre costume.",
    price: 45.0,
    image: "/images/products/cravattes/cravatte-19.jpeg",
    images: ["/images/products/cravattes/cravatte-19.jpeg"],
    category: "cravattes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-01",
    name: "Pochette Numéro 01",
    slug: "pochette-01",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-01.jpeg",
    images: ["/images/products/pochettes/pochette-01.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-02",
    name: "Pochette Numéro 02",
    slug: "pochette-02",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-02.jpeg",
    images: ["/images/products/pochettes/pochette-02.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-03",
    name: "Pochette Numéro 03",
    slug: "pochette-03",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-03.jpeg",
    images: ["/images/products/pochettes/pochette-03.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-04",
    name: "Pochette Numéro 04",
    slug: "pochette-04",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-04.jpeg",
    images: ["/images/products/pochettes/pochette-04.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-05",
    name: "Pochette Numéro 05",
    slug: "pochette-05",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-05.jpeg",
    images: ["/images/products/pochettes/pochette-05.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-06",
    name: "Pochette Numéro 06",
    slug: "pochette-06",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-06.jpeg",
    images: ["/images/products/pochettes/pochette-06.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-07",
    name: "Pochette Numéro 07",
    slug: "pochette-07",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-07.jpeg",
    images: ["/images/products/pochettes/pochette-07.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
  {
    id: "pochette-08",
    name: "Pochette Numéro 08",
    slug: "pochette-08",
    description: "Pochette de costume en soie élégante.",
    price: 25.0,
    image: "/images/products/pochettes/pochette-08.jpeg",
    images: ["/images/products/pochettes/pochette-08.jpeg"],
    category: "pochettes",
    sizes: ["Unique"],
    colors: ["Standard"],
    inStock: true,
    featured: false,
  },
];

export const services: Service[] = [
  {
    id: "serv-1",
    name: "Ourlet pantalon",
    slug: "ourlet-pantalon",
    description: "Raccourcir ou rallonger vos pantalons avec une finition impeccable. Ourlet simple ou invisible selon le tissu.",
    price: 15.0,
    image: "/images/services/ourlet.jpg",
    category: "ourlets",
  },
  {
    id: "serv-2",
    name: "Ourlet robe / jupe",
    slug: "ourlet-robe-jupe",
    description: "Ajustement de longueur de robe ou jupe, finition adaptée au tissu.",
    price: 20.0,
    image: "/images/services/ourlet-robe.jpg",
    category: "ourlets",
  },
  {
    id: "serv-3",
    name: "Cintrage veste / manteau",
    slug: "cintrage-veste",
    description: "Ajustement de la silhouette de votre veste ou manteau pour un tombé parfait.",
    price: 45.0,
    image: "/images/services/cintrage.jpg",
    category: "ajustements",
  },
  {
    id: "serv-4",
    name: "Remplacement fermeture éclair",
    slug: "remplacement-fermeture",
    description: "Changement complet de fermeture éclair sur veste, blouson, pantalon ou robe.",
    price: 35.0,
    image: "/images/services/fermeture.jpg",
    category: "réparations",
  },
  {
    id: "serv-5",
    name: "Reprise côtés chemise / top",
    slug: "reprise-cotes",
    description: "Ajustement de la largeur de vos chemises ou tops pour une coupe sur mesure.",
    price: 25.0,
    image: "/images/services/reprise.jpg",
    category: "ajustements",
  },
  {
    id: "serv-6",
    name: "Changement doublure",
    slug: "changement-doublure",
    description: "Remplacement complet de la doublure usée de votre veste, manteau ou blouson.",
    price: 85.0,
    image: "/images/services/doublure.jpg",
    category: "réparations",
  },
  {
    id: "serv-7",
    name: "Raccourcir manches",
    slug: "raccourcir-manches",
    description: "Ajustement de longueur des manches sur chemise, veste ou manteau.",
    price: 30.0,
    image: "/images/services/manches.jpg",
    category: "ajustements",
  },
  {
    id: "serv-8",
    name: "Transformation vêtement",
    slug: "transformation-vetement",
    description: "Transformez un vêtement existant en une nouvelle pièce unique. Devis personnalisé après consultation.",
    price: 60.0,
    image: "/images/services/transformation.jpg",
    category: "transformation",
  },
];

export const categories = [
  { name: "Robes", slug: "robes" },
  { name: "Vestes", slug: "vestes" },
  { name: "Pantalons", slug: "pantalons" },
  { name: "Tops", slug: "tops" },
  { name: "Jupes", slug: "jupes" },
  { name: "Chemises", slug: "chemises" },
  { name: "Manteaux", slug: "manteaux" },
  { name: "Combinaisons", slug: "combinaisons" },
  { name: "Cravattes", slug: "cravattes" },
  { name: "Pochettes", slug: "pochettes" },
];

export const serviceCategories = [
  { name: "Ourlets", slug: "ourlets" },
  { name: "Ajustements", slug: "ajustements" },
  { name: "Réparations", slug: "réparations" },
  { name: "Transformation", slug: "transformation" },
];
