import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: "serv-1",
    name: "Ourlet pantalon",
    slug: "ourlet-pantalon",
    description: "Raccourcir ou rallonger vos pantalons avec une finition impeccable. Ourlet simple ou invisible selon le tissu.",
    price: 15.0,
    image: "/images/services/ourlet.jpg",
    category: "ourlets",
  },
  {
    id: "serv-2",
    name: "Ourlet robe / jupe",
    slug: "ourlet-robe-jupe",
    description: "Ajustement de longueur de robe ou jupe, finition adaptée au tissu.",
    price: 20.0,
    image: "/images/services/ourlet-robe.jpg",
    category: "ourlets",
  },
  {
    id: "serv-3",
    name: "Cintrage veste / manteau",
    slug: "cintrage-veste",
    description: "Ajustement de la silhouette de votre veste ou manteau pour un tombé parfait.",
    price: 45.0,
    image: "/images/services/cintrage.jpg",
    category: "ajustements",
  },
  {
    id: "serv-4",
    name: "Remplacement fermeture éclair",
    slug: "remplacement-fermeture",
    description: "Changement complet de fermeture éclair sur veste, blouson, pantalon ou robe.",
    price: 35.0,
    image: "/images/services/fermeture.jpg",
    category: "réparations",
  },
  {
    id: "serv-5",
    name: "Reprise côtés chemise / top",
    slug: "reprise-cotes",
    description: "Ajustement de la largeur de vos chemises ou tops pour une coupe sur mesure.",
    price: 25.0,
    image: "/images/services/reprise.jpg",
    category: "ajustements",
  },
  {
    id: "serv-6",
    name: "Changement doublure",
    slug: "changement-doublure",
    description: "Remplacement complet de la doublure usée de votre veste, manteau ou blouson.",
    price: 85.0,
    image: "/images/services/doublure.jpg",
    category: "réparations",
  },
  {
    id: "serv-7",
    name: "Raccourcir manches",
    slug: "raccourcir-manches",
    description: "Ajustement de longueur des manches sur chemise, veste ou manteau.",
    price: 30.0,
    image: "/images/services/manches.jpg",
    category: "ajustements",
  },
  {
    id: "serv-8",
    name: "Transformation vêtement",
    slug: "transformation-vetement",
    description: "Transformez un vêtement existant en une nouvelle pièce unique. Devis personnalisé après consultation.",
    price: 60.0,
    image: "/images/services/transformation.jpg",
    category: "transformation",
  },
];

export const serviceCategories = [
  { name: "Ourlets", slug: "ourlets" },
  { name: "Ajustements", slug: "ajustements" },
  { name: "Réparations", slug: "réparations" },
  { name: "Transformation", slug: "transformation" },
];
