name: Build & Deploy Maelstrom dev

env:
  IMAGE_NAME: maelstrom
  REPO_NAME: maelstrom

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-dev:
    # On s'assure que l'événement est soit manuel, soit un push avec le tag [deploy]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy]'))
    runs-on:
      group: maelstrom-runners
      labels: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Idéalement remplace v4 par le SHA complet
        with:
          path: ${{ env.IMAGE_NAME }}
          # Le nettoyage est géré par défaut par checkout

      - name: Get Git SHA
        id: vars
        run: |
          cd "${{ env.IMAGE_NAME }}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image locally
        run: |
          docker build \
            -f "${{ env.IMAGE_NAME }}/docker/Dockerfile" \
            -t "${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}" \
            "${{ env.IMAGE_NAME }}"

      - name: Deploy stack
        env:
          # On passe le tag à l'environnement pour que le docker-compose.yml puisse l'utiliser via ${IMAGE_TAG}
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
          DATABASE_URL: file:/data/dev.db
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: |
          # Utilisation de docker stack deploy
          docker stack deploy -c "${{ env.IMAGE_NAME }}/docker/docker-compose.yml" "${{ env.IMAGE_NAME }}-stack"